/*
 * System call vector and marshalling for LKL.
 *
 * DO NOT EDIT-- this file is automatically generated.
 */


#ifdef RUMP_CLIENT
#include <rump/rumpuser_port.h>
#endif /* RUMP_CLIENT */

#include <asm/unistd.h>
#include <linux/rump_syscalls.h>


#ifdef RUMP_CLIENT
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <rump/rumpclient.h>

#define rsys_syscall(num, data, dlen, retval)	    rumpclient_syscall(num, data, dlen, retval)
#define rsys_seterrno(error) errno = error

#else /* !RUMP_CLIENT */

#include <linux/compiler.h>
#include <linux/types.h>
#include <linux/string.h>
#include <asm-generic/errno.h>

#include <rump/rump.h>
#include <rump/rumpuser.h>
int rump_syscall(int num, void *data, size_t dlen, register_t *retval);
#define rsys_syscall(num, data, dlen, retval)	    rump_syscall(num, data, dlen, retval)

#define rsys_seterrno(error) rumpuser_seterrno(error)

#endif


long rump___sysimpl_getpid(void)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));

	ret = lkl_syscall(__NR_getpid, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getpid);
__weak_alias(_,rump___sysimpl_getpid);
__strong_alias(_sys_,rump___sysimpl_getpid);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_write(unsigned int fd, const char * buf, size_t count)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)buf;
	params[2] = (long)count;

	ret = lkl_syscall(__NR_write, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_write);
__weak_alias(_,rump___sysimpl_write);
__strong_alias(_sys_,rump___sysimpl_write);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_close(unsigned int fd)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;

	ret = lkl_syscall(__NR_close, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_close);
__weak_alias(_,rump___sysimpl_close);
__strong_alias(_sys_,rump___sysimpl_close);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_unlink(const char * pathname)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)pathname;

	ret = lkl_syscall(__NR_unlink, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_unlink);
__weak_alias(_,rump___sysimpl_unlink);
__strong_alias(_sys_,rump___sysimpl_unlink);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_open(const char * filename, int flags, umode_t mode)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)flags;
	params[2] = (long)mode;

	ret = lkl_syscall(__NR_open, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_open);
__weak_alias(_,rump___sysimpl_open);
__strong_alias(_sys_,rump___sysimpl_open);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_creat(const char * filename, umode_t mode)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)mode;

	ret = lkl_syscall(__NR_creat, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_creat);
__weak_alias(_,rump___sysimpl_creat);
__strong_alias(_sys_,rump___sysimpl_creat);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_poll(void * ufds, unsigned int nfds, int timeout)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)ufds;
	params[1] = (long)nfds;
	params[2] = (long)timeout;

	ret = lkl_syscall(__NR_poll, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_poll);
__weak_alias(_,rump___sysimpl_poll);
__strong_alias(_sys_,rump___sysimpl_poll);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_read(unsigned int fd, char * buf, size_t count)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)buf;
	params[2] = (long)count;

	ret = lkl_syscall(__NR_read, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_read);
__weak_alias(_,rump___sysimpl_read);
__strong_alias(_sys_,rump___sysimpl_read);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_rename(const char * oldname, const char * newname)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)oldname;
	params[1] = (long)newname;

	ret = lkl_syscall(__NR_rename, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_rename);
__weak_alias(_,rump___sysimpl_rename);
__strong_alias(_sys_,rump___sysimpl_rename);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_flock(unsigned int fd, unsigned int cmd)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)cmd;

	ret = lkl_syscall(__NR_flock, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_flock);
__weak_alias(_,rump___sysimpl_flock);
__strong_alias(_sys_,rump___sysimpl_flock);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_chmod(const char * filename, umode_t mode)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)mode;

	ret = lkl_syscall(__NR_chmod, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_chmod);
__weak_alias(_,rump___sysimpl_chmod);
__strong_alias(_sys_,rump___sysimpl_chmod);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_mkdir(const char * pathname, umode_t mode)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)pathname;
	params[1] = (long)mode;

	ret = lkl_syscall(__NR_mkdir, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_mkdir);
__weak_alias(_,rump___sysimpl_mkdir);
__strong_alias(_sys_,rump___sysimpl_mkdir);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_rmdir(const char * pathname)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)pathname;

	ret = lkl_syscall(__NR_rmdir, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_rmdir);
__weak_alias(_,rump___sysimpl_rmdir);
__strong_alias(_sys_,rump___sysimpl_rmdir);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getdents64(unsigned int fd, void * dirent, unsigned int size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)dirent;
	params[2] = (long)size;

	ret = lkl_syscall(__NR_getdents64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getdents64);
__weak_alias(_,rump___sysimpl_getdents64);
__strong_alias(_sys_,rump___sysimpl_getdents64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_utimes(const char * filename, struct timeval * utimes)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)utimes;

	ret = lkl_syscall(__NR_utimes, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_utimes);
__weak_alias(_,rump___sysimpl_utimes);
__strong_alias(_sys_,rump___sysimpl_utimes);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_nanosleep(struct timespec * rqtp, struct timespec * rmtp)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)rqtp;
	params[1] = (long)rmtp;

	ret = lkl_syscall(__NR_nanosleep, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_nanosleep);
__weak_alias(_,rump___sysimpl_nanosleep);
__strong_alias(_sys_,rump___sysimpl_nanosleep);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_mknod(const char * filename, umode_t mode, unsigned int dev)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)mode;
	params[2] = (long)dev;

	ret = lkl_syscall(__NR_mknod, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_mknod);
__weak_alias(_,rump___sysimpl_mknod);
__strong_alias(_sys_,rump___sysimpl_mknod);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_mount(const char * dev_name, const char * dir_name, const char * type, unsigned long flags, void * data)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)dev_name;
	params[1] = (long)dir_name;
	params[2] = (long)type;
	params[3] = (long)flags;
	params[4] = (long)data;

	ret = lkl_syscall(__NR_mount, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_mount);
__weak_alias(_,rump___sysimpl_mount);
__strong_alias(_sys_,rump___sysimpl_mount);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_umount(const char * name, int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)name;
	params[1] = (long)flags;

	ret = lkl_syscall(__NR_umount, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_umount);
__weak_alias(_,rump___sysimpl_umount);
__strong_alias(_sys_,rump___sysimpl_umount);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_chdir(const char * filename)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;

	ret = lkl_syscall(__NR_chdir, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_chdir);
__weak_alias(_,rump___sysimpl_chdir);
__strong_alias(_sys_,rump___sysimpl_chdir);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_chroot(const char * filename)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;

	ret = lkl_syscall(__NR_chroot, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_chroot);
__weak_alias(_,rump___sysimpl_chroot);
__strong_alias(_sys_,rump___sysimpl_chroot);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getcwd(char * buf, unsigned long size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)buf;
	params[1] = (long)size;

	ret = lkl_syscall(__NR_getcwd, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getcwd);
__weak_alias(_,rump___sysimpl_getcwd);
__strong_alias(_sys_,rump___sysimpl_getcwd);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_utime(const char * filename, const struct utimbuf * buf)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)buf;

	ret = lkl_syscall(__NR_utime, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_utime);
__weak_alias(_,rump___sysimpl_utime);
__strong_alias(_sys_,rump___sysimpl_utime);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_ioctl(unsigned int fd, unsigned int cmd, unsigned long arg)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)cmd;
	params[2] = (long)arg;

	ret = lkl_syscall(__NR_ioctl, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_ioctl);
__weak_alias(_,rump___sysimpl_ioctl);
__strong_alias(_sys_,rump___sysimpl_ioctl);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_umask(int mask)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)mask;

	ret = lkl_syscall(__NR_umask, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_umask);
__weak_alias(_,rump___sysimpl_umask);
__strong_alias(_sys_,rump___sysimpl_umask);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getuid(void)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));

	ret = lkl_syscall(__NR_getuid, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getuid);
__weak_alias(_,rump___sysimpl_getuid);
__strong_alias(_sys_,rump___sysimpl_getuid);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getgid(void)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));

	ret = lkl_syscall(__NR_getgid, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getgid);
__weak_alias(_,rump___sysimpl_getgid);
__strong_alias(_sys_,rump___sysimpl_getgid);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_access(const char * filename, int mode)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)mode;

	ret = lkl_syscall(__NR_access, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_access);
__weak_alias(_,rump___sysimpl_access);
__strong_alias(_sys_,rump___sysimpl_access);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_truncate(const char * path, long length)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)length;

	ret = lkl_syscall(__NR_truncate, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_truncate);
__weak_alias(_,rump___sysimpl_truncate);
__strong_alias(_sys_,rump___sysimpl_truncate);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_sync(void)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));

	ret = lkl_syscall(__NR_sync, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_sync);
__weak_alias(_,rump___sysimpl_sync);
__strong_alias(_sys_,rump___sysimpl_sync);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_llseek(unsigned int fd, unsigned long offset_high, unsigned long offset_low, loff_t * result, unsigned int whence)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)offset_high;
	params[2] = (long)offset_low;
	params[3] = (long)result;
	params[4] = (long)whence;

	ret = lkl_syscall(__NR_llseek, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_llseek);
__weak_alias(_,rump___sysimpl_llseek);
__strong_alias(_sys_,rump___sysimpl_llseek);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fstat64(unsigned long fd, struct stat64 * statbuf)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)statbuf;

	ret = lkl_syscall(__NR_fstat64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fstat64);
__weak_alias(_,rump___sysimpl_fstat64);
__strong_alias(_sys_,rump___sysimpl_fstat64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fstatat64(unsigned int dfd, const char * filname, struct stat64 * statbuf, int flag)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)dfd;
	params[1] = (long)filname;
	params[2] = (long)statbuf;
	params[3] = (long)flag;

	ret = lkl_syscall(__NR_fstatat64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fstatat64);
__weak_alias(_,rump___sysimpl_fstatat64);
__strong_alias(_sys_,rump___sysimpl_fstatat64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_stat64(const char * filename, struct stat64 * statbuf)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)statbuf;

	ret = lkl_syscall(__NR_stat64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_stat64);
__weak_alias(_,rump___sysimpl_stat64);
__strong_alias(_sys_,rump___sysimpl_stat64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_lstat64(const char * filename, struct stat64 * statbuf)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)statbuf;

	ret = lkl_syscall(__NR_lstat64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_lstat64);
__weak_alias(_,rump___sysimpl_lstat64);
__strong_alias(_sys_,rump___sysimpl_lstat64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_statfs64(const char * path, size_t sz, struct statfs64 * buf)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)sz;
	params[2] = (long)buf;

	ret = lkl_syscall(__NR_statfs64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_statfs64);
__weak_alias(_,rump___sysimpl_statfs64);
__strong_alias(_sys_,rump___sysimpl_statfs64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_readlink(const char * path, char * buf, int bufsiz)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)buf;
	params[2] = (long)bufsiz;

	ret = lkl_syscall(__NR_readlink, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_readlink);
__weak_alias(_,rump___sysimpl_readlink);
__strong_alias(_sys_,rump___sysimpl_readlink);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_listxattr(const char * path, char * list, int bufsiz)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)list;
	params[2] = (long)bufsiz;

	ret = lkl_syscall(__NR_listxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_listxattr);
__weak_alias(_,rump___sysimpl_listxattr);
__strong_alias(_sys_,rump___sysimpl_listxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_llistxattr(const char * path, char * list, int bufsiz)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)list;
	params[2] = (long)bufsiz;

	ret = lkl_syscall(__NR_llistxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_llistxattr);
__weak_alias(_,rump___sysimpl_llistxattr);
__strong_alias(_sys_,rump___sysimpl_llistxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_flistxattr(int fd, char * list, int bufsiz)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)list;
	params[2] = (long)bufsiz;

	ret = lkl_syscall(__NR_flistxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_flistxattr);
__weak_alias(_,rump___sysimpl_flistxattr);
__strong_alias(_sys_,rump___sysimpl_flistxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getxattr(const char * path, const char * name, void * value, size_t size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;

	ret = lkl_syscall(__NR_getxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getxattr);
__weak_alias(_,rump___sysimpl_getxattr);
__strong_alias(_sys_,rump___sysimpl_getxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_lgetxattr(const char * path, const char * name, void * value, size_t size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;

	ret = lkl_syscall(__NR_lgetxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_lgetxattr);
__weak_alias(_,rump___sysimpl_lgetxattr);
__strong_alias(_sys_,rump___sysimpl_lgetxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fgetxattr(int fd, const char * name, void * value, size_t size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;

	ret = lkl_syscall(__NR_fgetxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fgetxattr);
__weak_alias(_,rump___sysimpl_fgetxattr);
__strong_alias(_sys_,rump___sysimpl_fgetxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_setxattr(const char * path, const char * name, const void * value, size_t size, int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;
	params[4] = (long)flags;

	ret = lkl_syscall(__NR_setxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_setxattr);
__weak_alias(_,rump___sysimpl_setxattr);
__strong_alias(_sys_,rump___sysimpl_setxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_lsetxattr(const char * path, const char * name, const void * value, size_t size, int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;
	params[4] = (long)flags;

	ret = lkl_syscall(__NR_lsetxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_lsetxattr);
__weak_alias(_,rump___sysimpl_lsetxattr);
__strong_alias(_sys_,rump___sysimpl_lsetxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fsetxattr(int fd, const char * name, const void * value, size_t size, int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)name;
	params[2] = (long)value;
	params[3] = (long)size;
	params[4] = (long)flags;

	ret = lkl_syscall(__NR_fsetxattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fsetxattr);
__weak_alias(_,rump___sysimpl_fsetxattr);
__strong_alias(_sys_,rump___sysimpl_fsetxattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_symlink(const char * oldname, const char * newname)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)oldname;
	params[1] = (long)newname;

	ret = lkl_syscall(__NR_symlink, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_symlink);
__weak_alias(_,rump___sysimpl_symlink);
__strong_alias(_sys_,rump___sysimpl_symlink);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_link(const char * oldname, const char * newname)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)oldname;
	params[1] = (long)newname;

	ret = lkl_syscall(__NR_link, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_link);
__weak_alias(_,rump___sysimpl_link);
__strong_alias(_sys_,rump___sysimpl_link);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_chown(const char * filename, uid32_t uid, gid32_t gid)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)filename;
	params[1] = (long)uid;
	params[2] = (long)gid;

	ret = lkl_syscall(__NR_chown, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_chown);
__weak_alias(_,rump___sysimpl_chown);
__strong_alias(_sys_,rump___sysimpl_chown);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_pread64(unsigned int fd, char * buf, size_t count, loff_t pos)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)buf;
	params[2] = (long)count;
	params[3] = (long)pos;

	ret = lkl_syscall(__NR_pread64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_pread64);
__weak_alias(_,rump___sysimpl_pread64);
__strong_alias(_sys_,rump___sysimpl_pread64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_pwrite64(unsigned int fd, const char * buf, size_t count, loff_t pos)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)buf;
	params[2] = (long)count;
	params[3] = (long)pos;

	ret = lkl_syscall(__NR_pwrite64, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_pwrite64);
__weak_alias(_,rump___sysimpl_pwrite64);
__strong_alias(_sys_,rump___sysimpl_pwrite64);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fsync(unsigned int fd)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;

	ret = lkl_syscall(__NR_fsync, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fsync);
__weak_alias(_,rump___sysimpl_fsync);
__strong_alias(_sys_,rump___sysimpl_fsync);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fdatasync(unsigned int fd)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;

	ret = lkl_syscall(__NR_fdatasync, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fdatasync);
__weak_alias(_,rump___sysimpl_fdatasync);
__strong_alias(_sys_,rump___sysimpl_fdatasync);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_removexattr(const char * path, const char * name)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)path;
	params[1] = (long)name;

	ret = lkl_syscall(__NR_removexattr, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_removexattr);
__weak_alias(_,rump___sysimpl_removexattr);
__strong_alias(_sys_,rump___sysimpl_removexattr);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_utimensat(int dirfd, const char * path, struct timespec * utimes, int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)dirfd;
	params[1] = (long)path;
	params[2] = (long)utimes;
	params[3] = (long)flags;

	ret = lkl_syscall(__NR_utimensat, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_utimensat);
__weak_alias(_,rump___sysimpl_utimensat);
__strong_alias(_sys_,rump___sysimpl_utimensat);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fallocate(int fd, int mode, loff_t offset, loff_t len)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)mode;
	params[2] = (long)offset;
	params[3] = (long)len;

	ret = lkl_syscall(__NR_fallocate, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fallocate);
__weak_alias(_,rump___sysimpl_fallocate);
__strong_alias(_sys_,rump___sysimpl_fallocate);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_socket(int family, int type, int protocol)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)family;
	params[1] = (long)type;
	params[2] = (long)protocol;

	ret = lkl_syscall(__NR_socket, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_socket);
__weak_alias(_,rump___sysimpl_socket);
__strong_alias(_sys_,rump___sysimpl_socket);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_recvmsg(int fd, struct msghdr * msg, unsigned int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)msg;
	params[2] = (long)flags;

	ret = lkl_syscall(__NR_recvmsg, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_recvmsg);
__weak_alias(_,rump___sysimpl_recvmsg);
__strong_alias(_sys_,rump___sysimpl_recvmsg);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_recvfrom(int fd, void * ubuf, size_t size, unsigned int flags, struct sockaddr * addr, int * addr_len)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)ubuf;
	params[2] = (long)size;
	params[3] = (long)flags;
	params[4] = (long)addr;
	params[5] = (long)addr_len;

	ret = lkl_syscall(__NR_recvfrom, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_recvfrom);
__weak_alias(_,rump___sysimpl_recvfrom);
__strong_alias(_sys_,rump___sysimpl_recvfrom);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_sendto(int fd, void * buff, size_t len, unsigned int flags, struct sockaddr * addr, int addr_len)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)buff;
	params[2] = (long)len;
	params[3] = (long)flags;
	params[4] = (long)addr;
	params[5] = (long)addr_len;

	ret = lkl_syscall(__NR_sendto, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_sendto);
__weak_alias(_,rump___sysimpl_sendto);
__strong_alias(_sys_,rump___sysimpl_sendto);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_sendmsg(int fd, struct msghdr * msg, unsigned int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)msg;
	params[2] = (long)flags;

	ret = lkl_syscall(__NR_sendmsg, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_sendmsg);
__weak_alias(_,rump___sysimpl_sendmsg);
__strong_alias(_sys_,rump___sysimpl_sendmsg);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_sendmmsg(int fd, struct mmsghdr * mmsg, unsigned int vlen, unsigned int flags)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)mmsg;
	params[2] = (long)vlen;
	params[3] = (long)flags;

	ret = lkl_syscall(__NR_sendmmsg, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_sendmmsg);
__weak_alias(_,rump___sysimpl_sendmmsg);
__strong_alias(_sys_,rump___sysimpl_sendmmsg);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getsockname(int fd, struct sockaddr * usockaddr, void * usockaddr_len)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)usockaddr;
	params[2] = (long)usockaddr_len;

	ret = lkl_syscall(__NR_getsockname, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getsockname);
__weak_alias(_,rump___sysimpl_getsockname);
__strong_alias(_sys_,rump___sysimpl_getsockname);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getpeername(int fd, struct sockaddr * usockaddr, int * usockaddr_len)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)usockaddr;
	params[2] = (long)usockaddr_len;

	ret = lkl_syscall(__NR_getpeername, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getpeername);
__weak_alias(_,rump___sysimpl_getpeername);
__strong_alias(_sys_,rump___sysimpl_getpeername);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_setsockopt(int fd, int level, int optname, void * optval, int optlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)level;
	params[2] = (long)optname;
	params[3] = (long)optval;
	params[4] = (long)optlen;

	ret = lkl_syscall(__NR_setsockopt, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_setsockopt);
__weak_alias(_,rump___sysimpl_setsockopt);
__strong_alias(_sys_,rump___sysimpl_setsockopt);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_getsockopt(int fd, int level, int optname, char * optval, int * optlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)level;
	params[2] = (long)optname;
	params[3] = (long)optval;
	params[4] = (long)optlen;

	ret = lkl_syscall(__NR_getsockopt, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_getsockopt);
__weak_alias(_,rump___sysimpl_getsockopt);
__strong_alias(_sys_,rump___sysimpl_getsockopt);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_bind(int fd, struct sockaddr * umyaddr, int addrlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)umyaddr;
	params[2] = (long)addrlen;

	ret = lkl_syscall(__NR_bind, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_bind);
__weak_alias(_,rump___sysimpl_bind);
__strong_alias(_sys_,rump___sysimpl_bind);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_connect(int fd, struct sockaddr * uservaddr, int addrlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)uservaddr;
	params[2] = (long)addrlen;

	ret = lkl_syscall(__NR_connect, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_connect);
__weak_alias(_,rump___sysimpl_connect);
__strong_alias(_sys_,rump___sysimpl_connect);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_listen(int fd, int backlog)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)backlog;

	ret = lkl_syscall(__NR_listen, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_listen);
__weak_alias(_,rump___sysimpl_listen);
__strong_alias(_sys_,rump___sysimpl_listen);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_accept(int fd, struct sockaddr * upeer_sockaddr, int * upeer_addrlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)upeer_sockaddr;
	params[2] = (long)upeer_addrlen;

	ret = lkl_syscall(__NR_accept, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_accept);
__weak_alias(_,rump___sysimpl_accept);
__strong_alias(_sys_,rump___sysimpl_accept);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_writev(unsigned long fd, const struct iovec * vec, unsigned long vlen)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)vec;
	params[2] = (long)vlen;

	ret = lkl_syscall(__NR_writev, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_writev);
__weak_alias(_,rump___sysimpl_writev);
__strong_alias(_sys_,rump___sysimpl_writev);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)cmd;
	params[2] = (long)arg;

	ret = lkl_syscall(__NR_fcntl, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_fcntl);
__weak_alias(_,rump___sysimpl_fcntl);
__strong_alias(_sys_,rump___sysimpl_fcntl);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_select(int n, void * inp, void * outp, void * exp, struct timeval * tvp)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)n;
	params[1] = (long)inp;
	params[2] = (long)outp;
	params[3] = (long)exp;
	params[4] = (long)tvp;

	ret = lkl_syscall(__NR_select, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_select);
__weak_alias(_,rump___sysimpl_select);
__strong_alias(_sys_,rump___sysimpl_select);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_epoll_create(int size)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)size;

	ret = lkl_syscall(__NR_epoll_create, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_epoll_create);
__weak_alias(_,rump___sysimpl_epoll_create);
__strong_alias(_sys_,rump___sysimpl_epoll_create);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_epoll_ctl(int epfd, int op, int fd, struct epoll_event * event)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)epfd;
	params[1] = (long)op;
	params[2] = (long)fd;
	params[3] = (long)event;

	ret = lkl_syscall(__NR_epoll_ctl, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_epoll_ctl);
__weak_alias(_,rump___sysimpl_epoll_ctl);
__strong_alias(_sys_,rump___sysimpl_epoll_ctl);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_epoll_wait(int epfd, struct epoll_event * events, int maxevents, int timeout)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)epfd;
	params[1] = (long)events;
	params[2] = (long)maxevents;
	params[3] = (long)timeout;

	ret = lkl_syscall(__NR_epoll_wait, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_epoll_wait);
__weak_alias(_,rump___sysimpl_epoll_wait);
__strong_alias(_sys_,rump___sysimpl_epoll_wait);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_shutdown(int fd, int how)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fd;
	params[1] = (long)how;

	ret = lkl_syscall(__NR_shutdown, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_shutdown);
__weak_alias(_,rump___sysimpl_shutdown);
__strong_alias(_sys_,rump___sysimpl_shutdown);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_pipe(int * fildes)
{
	int ret;
	long params[6];

	memset(params, 0, sizeof(params));
	params[0] = (long)fildes;

	ret = lkl_syscall(__NR_pipe, params);
	/* errno handling */
	if (ret < 0) {
		rsys_seterrno(-ret);
		ret = -1;
	}
	return ret;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_pipe);
__weak_alias(_,rump___sysimpl_pipe);
__strong_alias(_sys_,rump___sysimpl_pipe);
#endif /* RUMP_KERNEL_IS_LIBC */


long rump___sysimpl_reboot(int magic1, int magic2, unsigned int cmd, void * arg)
{
	lkl_sys_halt();

	/* should not return */
	return 0;
}
#ifdef RUMP_KERNEL_IS_LIBC
__weak_alias(,rump___sysimpl_reboot);
__weak_alias(_,rump___sysimpl_reboot);
__strong_alias(_sys_,rump___sysimpl_reboot);
#endif /* RUMP_KERNEL_IS_LIBC */
