
#CFLAGS_rumpdev_pci.o=-I$(ARCH_DIR)/libpci/ -I$(srctree)/../src/common/include \
-I$(srctree)/../src/sys -I$(srctree)/../../rumprun/platform/hw/pci/

obj-y = rumpdev_pci.o

CFLAGS_rumpdev_pci.o=-g -O0

